#!/bin/bash                                                          
#PBS -q parallel
#PBS -l nodes=1:ppn=24
#PBS -l mem=48gb
#PBS -l cput=8144:00:00 
#PBS -N meso

cd $PBS_O_WORKDIR
export GAUSS_SCRDIR=$PBS_O_WORKDIR
export PATH=/scratch/bochen/Python-2.7.18/bin:$PATH
export PYTHONPATH=/scratch/bochen/Python-2.7.18

module load Gaussian/16

date

perl xp_pes2020.1.4.2.1.pl \
45 \
1.com 1.com \
meso-TS_91_2.com	\
meso-TS_88_2.com	\
meso-TS_85_2.com	\
meso-TS_82_2.com	\
meso-TS_79_2.com	\
meso-TS_76_2.com	\
meso-TS_73_2.com	\
meso-TS_70_2.com	\
meso-TS_67_2.com	\
meso-TS_64_2.com	\
meso-TS_61_2.com	\
meso-TS_58_2.com	\
meso-TS_55_2.com	\
meso-TS_52_2.com	\
meso-TS_49_2.com	\
meso-TS_46_2.com	\
meso-TS_43_2.com	\
meso-TS_40_2.com	\
meso-TS_37_2.com	\
meso-TS_34_2.com	\
meso-TS_31_2.com	\
meso-TS_28_2.com	\
meso-TS_25_2.com	\
meso-TS_22_2.com	\
meso-TS_19_2.com	\
meso-TS_16_2.com	\
meso-TS_13_2.com	\
meso-TS_10_2.com	\
meso-TS_7_2.com	\
meso-TS_4_2.com	\
meso-TS_1_2.com	\
meso-TS_0_1.com	\
meso-TS_1_1.com	\
meso-TS_4_1.com	\
meso-TS_7_1.com	\
meso-TS_10_1.com	\
meso-TS_13_1.com	\
meso-TS_16_1.com	\
meso-TS_19_1.com	\
meso-TS_22_1.com	\
meso-TS_25_1.com	\
meso-TS_28_1.com	\
meso-TS_30_1.com	\
1.2 1.15 1.10 1.05 1.00 0.975 0.95 \
C6H12 3 vdw 1.2 0.075 1 py 
date
