#!/bin/bash                                                          
#PBS -q parallel
#PBS -l nodes=1:ppn=24
#PBS -l mem=48gb
#PBS -l cput=1424:00:00 
#PBS -N meso

# Define working directory, copy relevant data, and change directory
#export SCRATCH_DIR=/scratch/$USER/jobs/$PBS_JOBID
#mkdir -p $SCRATCH_DIR
cd $PBS_O_WORKDIR
#cp -r * $SCRATCH_DIR
#cd $SCRATCH_DIR
#export GAUSS_SCRDIR=$SCRATCH_DIR
export GAUSS_SCRDIR=$PBS_O_WORKDIR

# Load environment for Gaussian
module load Gaussian/16
module load Mathematica/7.0.1
#module load Python/3.7.0-foss-2018b

# Define number of cores and number of nodes
#export NPROCS=`wc -l < $PBS_NODEFILE`
#export NODES=`uniq $PBS_NODEFILE | awk '{printf("%s,", $0)}' | sed
#'s/.$//'`

# Insert nodes and cores in the header of the input file
#echo "%NProcShared=$NPROCS" > INPUT
#echo "%LindaWorkers=$NODES" >> INPUT
#cat my_input_file.com >> INPUT

#export jobname=erythro-4-TS
#g16 < $jobname.*[gjf,com] >& $jobname.g16
date

perl xp_pes2020.1.4.2.1.pl \
5 \
1.com 1.com meso-TS_91_2.com	\
meso-TS_0_1.com	\
meso-TS_30_1.com	\
1.2 1.15 1.10 1.05 1.00 0.975 0.95 \
C6H12 3 vdw 1.2 0.075 1 math

date
